name: deploy

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and deploy website
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/madnlp"
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "Github action runner"
          python3 -m venv venv
          source venv/bin/activate
          pip3 install .
          python3 -m madsuiteio deploy
